Don't charge money when no no addition added
tubbo/openrct2-benchwarmer pull request #15
Opened 2020-09-06 21:20 UTC by pencil

This avoids charging money for the same addition over and over again when running the plugin multiple times.

2020-09-08 17:13 UTC, tubbo requested changes

2020-09-08 17:13 UTC, tubbo commented on src/add.js
> +      if (path.addition !== bench) {
this could probably be tacked onto the condition above:

```javascript
if ((x % 2 === y % 2) && (path.addition !== bench)) {
```

2020-09-08 17:13 UTC, tubbo commented on src/add.js
> +      if (path.addition !== bin) {
and this one should be tacked onto the `else`:

```javascript
} else if (path.addition !== bin) {
```

2020-09-08 17:13 UTC, tubbo commented on src/add.js
> +      if (path.addition !== bin) {
and here as well:

```javascript
if ((buildBinsOnAllSlopedPaths || (x % 2 === y % 2)) && (path.addition !== bin)) {
```

2020-09-13 19:38 UTC, pencil commented
I refactored the code a bit. Also noticed that the prices were previously set too low: RCT2 expresses all prices and cash amounts in dimes. A price of `5` is therefor 50 cents instead of $5.
![dimes](https://user-images.githubusercontent.com/812086/93026837-d8043580-f5bd-11ea-9b46-6ef48945a5b4.gif)

2020-09-16 13:55 UTC, tubbo approved these changes
love it. thank you!

2020-09-16 13:55 UTC, merged

2020-09-16 16:09 UTC, RundesBalli commented
Works fine! :)